class Product:
    def __init__(self):
        self.product_id = ''
        self.product_name = ''
        self.rating = ''
        self.positive_reviews = ''
        self.negativ_reviews = ''
        self.price = ''
        self.is_available = ''
        self.measure = ''
        self.product_url = ''
        self.vender_name = ''
        self.portal_name = ''
        self.category_name = ''
        self.category_url = ''